version: '3.8'

services:
  fragments:
    build: .
    init: true
    ports:
      - '8080:8080'
    volumes:
      - ./tests/.htpasswd:/app/tests/.htpasswd
    environment:
      - API_URL=http://localhost:8080
      - HTPASSWD_FILE=tests/.htpasswd
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - AWS_REGION=us-east-1
      - AWS_S3_ENDPOINT_URL=http://localstack:4566
      - AWS_DYNAMODB_ENDPOINT_URL=http://localstack:4566
      - AWS_S3_BUCKET_NAME=fragments
      - AWS_DYNAMODB_TABLE_NAME=fragments
      - AWS_COGNITO_POOL_ID=us-east-1_6yzJfIpJw
      - AWS_COGNITO_CLIENT_ID=63fjeahq4u2a1vrsrdthd1r29
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test
    depends_on:
      - localstack
      - dynamodb-local

  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,dynamodb
      - DEFAULT_REGION=us-east-1

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    command: ['-jar', 'DynamoDBLocal.jar', '-inMemory']
